### ISSUE TITLE
craft ____ button fails

### ISSUE THREAD

**Issue by shrugs** [zeppelinos/crafty#30]
the "craft ____" button doesn't estimate gas at all, which probably means it's failing somehow

only happens on non-basic tokens

**Comment by nventuro** [comment]
By 'non-basic' do you mean you're trying to craft a token with ingredients? Have you approved all tokens, and do you have enough balance to perform the craft? [This test](https://github.com/zeppelinos/crafty/blob/master/test/Crafty.js#L71) tests the craft function for a non-basic token (and passes).
