### ISSUE TITLE
"All craftable tokens" mentioned twice

### ISSUE THREAD

**Issue by elopio** [zeppelinos/crafty#67]
The subheader of the `Discover` page says:
`Here's a list of all the craftable tokens, have fun!`
Right below that, there's a section title that says:
`All Craftable Tokens`

![screenshot from 2018-05-22 00-57-41](https://user-images.githubusercontent.com/617831/40346790-257991fa-5d5b-11e8-85a1-5f778e242be1.png)

This makes the subheader repetitive. It might not be necessary at all, so what about removing it? 
Or if you want to keep, what about changing it to something like: "Here are the tokens, have fun!"

**Comment by nventuro** [comment]
Closed in e8185ad8fc4b0b6fff4db34ce2b6ffdabff6477b
