### ISSUE TITLE
No explanation of recipes without ingredients

### ISSUE THREAD

**Issue by elopio** [zeppelinos/crafty#70]
On the `New Recipe` page, you can create a recipe without ingredients. However, there is no explanation of what happens in that case.

When all the ingredients have been removed, we could say something like:
"A recipe without ingredients can be freely created by everybody"

**Comment by nventuro** [comment]
The `Crafty` contract does not, in fact, allow for users to create ingredient-less tokens. The UI is currently missing this validation, see #36
